name: Hello from AWS

on:
  push:

permissions:
  id-token: write

jobs:
  greeting:
    environment: staging
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

    - name: Print assumed role
      run: aws sts get-caller-identity
